$env:GDAL_DATA = 'C:\\PROGRA~1\\QGIS33~1.2\\apps\\gdal\\share\\gdal'
$env:GDAL_DRIVER_PATH = 'C:\\PROGRA~1\\QGIS33~1.2\\apps\\gdal\\lib\\gdalplugins'
$env:GDAL_FILENAME_IS_UTF8 = 'YES'
$env:GISBASE = 'C:/PROGRA~1/QGIS33~1.2/apps/grass/grass83'
$env:GRASS_PROJSHARE: 'C:\\PROGRA~1\\QGIS33~1.2\\share\\proj',
$env:GRASS_PYTHON: 'C:\\PROGRA~1\\QGIS33~1.2\\bin\\python3.exe',
$env:O4W_QT_BINARIES: 'C:/PROGRA~1/QGIS33~1.2/apps/Qt5/bin',
$env:O4W_QT_HEADERS: 'C:/PROGRA~1/QGIS33~1.2/apps/Qt5/include',
$env:O4W_QT_LIBRARIES: 'C:/PROGRA~1/QGIS33~1.2/apps/Qt5/lib',
$env:O4W_QT_PLUGINS: 'C:/PROGRA~1/QGIS33~1.2/apps/Qt5/plugins',
$env:O4W_QT_PREFIX: 'C:/PROGRA~1/QGIS33~1.2/apps/Qt5',
$env:O4W_QT_TRANSLATIONS: 'C:/PROGRA~1/QGIS33~1.2/apps/Qt5/translations',
$env:OSGEO4W_ROOT: 'C:\\PROGRA~1\\QGIS33~1.2',
$env:PATH: 'C:\\PROGRA~1\\QGIS33~1.2\\apps\\qgis\\bin;C:\\PROGRA~1\\QGIS33~1.2\\apps\\grass\\grass83\\lib;C:\\PROGRA~1\\QGIS33~1.2\\apps\\grass\\grass83\\bin;C:\\PROGRA~1\\QGIS33~1.2\\apps\\qt5\\bin;C:\\PROGRA~1\\QGIS33~1.2\\apps\\Python39\\Scripts;C:\\PROGRA~1\\QGIS33~1.2\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\system32\\WBem',
$env:PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
$env:PDAL_DRIVER_PATH: 'C:\\PROGRA~1\\QGIS33~1.2\\apps\\pdal\\plugins',
$env:POWERSHELL_DISTRIBUTION_CHANNEL: 'MSI:Windows 10 Pro',
$env:PROCESSOR_ARCHITECTURE: 'AMD64',
$env:PROCESSOR_IDENTIFIER: 'AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD',
$env:PROCESSOR_LEVEL: '25',
$env:PROCESSOR_REVISION: '6102',
$env:PROGRAMDATA: 'C:\\ProgramData',
$env:PROGRAMFILES: 'C:\\Program Files',
$env:PROGRAMFILES(X86): 'C:\\Program Files (x86)',
$env:PROGRAMW6432: 'C:\\Program Files',
$env:PROJ_LIB: 'C:\\PROGRA~1\\QGIS33~1.2\\share\\proj',
$env:PSMODULEPATH: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
$env:PUBLIC: 'C:\\Users\\Public',
$env:PYTHONHOME: 'C:\\PROGRA~1\\QGIS33~1.2\\apps\\Python39',
$env:PYTHONPATH: 'C:\\PROGRA~1\\QGIS33~1.2\\apps\\grass\\grass83\\etc\\python;',
$env:PYTHONUTF8: '1',
$env:QGIS_PREFIX_PATH: 'C:/PROGRA~1/QGIS33~1.2/apps/qgis',
$env:QGIS_WIN_APP_NAME: 'QGIS 3.32\\QGIS Desktop 3.32.2',
$env:QT_PLUGIN_PATH: 'C:\\PROGRA~1\\QGIS33~1.2\\apps\\qgis\\qtplugins;C:\\PROGRA~1\\QGIS33~1.2\\apps\\qt5\\plugins',
$env:SESSIONNAME: 'Console',
$env:SSL_CERT_DIR: 'C:\\PROGRA~1\\QGIS33~1.2\\apps\\openssl\\certs',
$env:SSL_CERT_FILE: 'C:\\PROGRA~1\\QGIS33~1.2\\bin\\curl-ca-bundle.crt',
$env:SYSTEMDRIVE: 'C:',
$env:SYSTEMROOT: 'C:\\Windows',
$env:TEMP: 'C:\\Users\\MBUKOW~1\\AppData\\Local\\Temp',
$env:TMP: 'C:\\Users\\MBUKOW~1\\AppData\\Local\\Temp',
$env:USERDOMAIN: 'grindelwald',
$env:USERDOMAIN_ROAMINGPROFILE: 'grindelwald',
$env:USERNAME: 'mbukowski',
$env:USERPROFILE: 'C:\\Users\\mbukowski',
$env:VSI_CACHE: 'TRUE',
$env:VSI_CACHE_SIZE: '1000000',
$env:WINDIR: 'C:\\Windows',
$env:QT_QPA_PLATFORM: 'windows:altgr',
$env:QT3D_RENDERER: 'opengl',
$env:HOME: 'C:\\Users\\mbukowski'
}


